### ISSUE TITLE
Allow algorithm definition outside XML file

### ISSUE THREAD

**Issue by pradal** [AgriculturalModelExchangeInitiative/Crop2ML#11]
CropML allows to define algorithm in different languages (Python, Fortran, C#, ...).
However, spaces and tabs are not kept as is. This is an issue for languages, like Python or Fortran.

Please allow to define algorithm part in an external file  (code.f90, code.py, code.cpp, ...).
This file will be referenced in the CropML xml definition.

**Comment by cyrillemidingoyi** [comment]
Already done
